name: bug_report_template
description: File a bug report
title: "[Bug]"
labels: ["backlog"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report and please fill out all necessary fields!
  - type: input
    id: commit
    attributes:
      label: Commit version
      description: Which commit do you use?
      placeholder: ex. 1212121
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What priority for this bug
      options:
        - High
        - Middle
        - Low
      default: 0
    validations:
      required: true
  - type: textarea
    id: what_expectation
    attributes:
      label: What expects to be happened?
      description: Describe what expects to be happened in this commit version
      placeholder: What do you want
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Describe what happened in this commit version
      placeholder: What do you see
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Describe steps to reproduce this bug
      placeholder: Steps to reproduce this bug at details
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log output
      description: Please copy and paste log output here
      render: shell
    validations:
      required: true
